### ISSUE TITLE
Getting Subspace is not a constructor error while connecting to Web3 provider

### ISSUE THREAD

**Issue by Sahilsen** [embarklabs/subspace#85]
```
var Web3 = require('web3')
var Subspace = require('@embarklabs/subspace');
var url = 'WEb3_http_endpoint'
var web3 = new Web3(url)
var subspace = new Subspace(web3);
subspace.init().then(() => {
	subspace.trackBlockNumber().subscribe(blockNumber => {
		console.log("The latest block number is: ", blockNumber);
	});
});
```
Hello, in the above code I'm facing an issue, 'Subspace is not a constructor' error

**Comment by acolytec3** [comment]
@Sahilsen Are you using Node? If so, you need to use `const subspace = new Subspace.default(web3);`

Here's a complete working example https://github.com/acolytec3/ArgoDisco/

**Comment by Sahilsen** [comment]
Hi @acolytec3 thank you so much for the tip it worked just fine.

**Comment by acolytec3** [comment]
@richard-ramos Regarding this issue, do we just need to add a note to the documentation to note that when using Subspace in Node/CommonJS environments, the constructor declaration needs to be `new Subspace.default...`?  I just discovered it by trial and error.
